[project]
name = "mom-id"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopandas>=1.0.1",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
